services:
  # MongoDB Service
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - kalMongoDB:/data/db

  # LMS API Service
  api:
    build: .
    ports:
    - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes: 
      - app-logs:/usr/src/app/logs
    depends_on:
      - mongodb
volumes:
  kalMongoDB:
  app-logs: